export const pricingPlans = [
  {
    plan: "Trial",
    monthlyPrice: "Try now",
    yearlyPrice: "Try now",
    description: "Get personalised template",
    features: [
      "25+ data sources",
      "GPT-4, LinkedIn, and others",
      "Access to Slack community",
      "10+ templates to scale your outbound",
    ],
    sub_features: ["Explore product capabilities"],
    isPopular: false,
    buttonLabel: "Try now",
  },
  {
    plan: "Growth",
    monthlyPrice: "$229",
    yearlyPrice: "$2,290",
    original_price: "$459",
    discount: "50% off",
    features: [
      "8,000 Credits",
      "Webhook, HTTP API",
      "Credit rollover (up to 2x plan credits)",
      "Outbound email integrations like Instantly, Smartlead",
      "Dedicated 3 hours from Bitscale expert",
    ],
    sub_features: [
      "Unlimited leads search",
      "Fully enriched 5,000 leads",
      "Personalized outreach at scale",
    ],
    isPopular: false,
    buttonLabel: "Continue with Growth",
  },
  {
    plan: "Booster",
    monthlyPrice: "$499",
    yearlyPrice: "$4,990",
    original_price: "$999",
    discount: "50% off",
    features: [
      "25,000 Credits",
      "Webhook, HTTP API",
      "Credit rollover (up to 2x plan credits)",
      "Outbound email integrations like Instantly, Smartlead",
      "Dedicated 3 hours from Bitscale expert",
      "Advanced models like Claude Sonnet",
      "Dedicated 8 hours from Bitscale expert",
      "2-way Hubspot integration",
    ],
    sub_features: [
      "Unlimited leads search",
      "Fully enriched 15,000 leads",
      "Personalized outreach at scale",
    ],
    isPopular: true,
    buttonLabel: "Continue with Booster",
  },
  {
    plan: "Enterprise",
    monthlyPrice: "Contact Us",
    yearlyPrice: "Contact Us",
    description: "For individual pricing",
    features: [
      "Data privacy certification",
      "Priority support",
      "Dedicated Bitscale expert",
      "Private Slack channel",
      "Collaborative workspace and templates",
    ],
    sub_features: [
      "Perfect for high-volume end-to-end CRM data enrichment",
      "Unlimited list of leads with unlimited data points",
    ],
    isPopular: false,
    buttonLabel: "Contact Sales",
  },
];
